-- MySQL Script generated by MySQL Workbench
-- Wed Nov 16 09:01:48 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mis
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mis` ;

-- -----------------------------------------------------
-- Schema mis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mis` DEFAULT CHARACTER SET utf8 ;
USE `mis` ;

-- -----------------------------------------------------
-- Table `mis`.`study_team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mis`.`study_team` ;

CREATE TABLE IF NOT EXISTS `mis`.`study_team` (
  `id` INT NOT NULL,
  `desc` VARCHAR(4000) NULL COMMENT '团队描述\n',
  `study_direction` VARCHAR(2000) NULL COMMENT '研究方向\n',
  `subjects_task` VARCHAR(2000) NULL COMMENT '研究课题任务\n',
  `relative_articles` VARCHAR(2000) NULL COMMENT '发表文章\n',
  `type` INT NULL,
  `team_group_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '研究团队';


-- -----------------------------------------------------
-- Table `mis`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mis`.`user` ;

CREATE TABLE IF NOT EXISTS `mis`.`user` (
  `id` INT NOT NULL,
  `username` VARCHAR(20) NULL,
  `password` VARCHAR(16) NULL,
  `status` VARCHAR(1) NULL,
  `desc` VARCHAR(1000) NULL,
  `team_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_1_idx` (`team_id` ASC),
  CONSTRAINT `fk_user_1`
    FOREIGN KEY (`team_id`)
    REFERENCES `mis`.`study_team` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mis`.`news`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mis`.`news` ;

CREATE TABLE IF NOT EXISTS `mis`.`news` (
  `id` INT NOT NULL,
  `subject` VARCHAR(100) NULL,
  `content` VARCHAR(2000) NULL,
  `status` VARCHAR(1) NULL COMMENT '发布状态\n',
  `create_date` DATE NULL,
  `update_date` DATE NULL,
  `create_by` INT NULL,
  `publish_date` DATE NULL,
  `actical_id` INT NULL,
  `actical_link` VARCHAR(45) NULL,
  `actical_author` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_t_xwdt_1_idx` (`create_by` ASC),
  CONSTRAINT `fk_t_xwdt_1`
    FOREIGN KEY (`create_by`)
    REFERENCES `mis`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '新闻动态';


-- -----------------------------------------------------
-- Table `mis`.`notification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mis`.`notification` ;

CREATE TABLE IF NOT EXISTS `mis`.`notification` (
  `id` INT NOT NULL,
  `subject` VARCHAR(100) NULL,
  `content` VARCHAR(4000) NULL,
  `status` VARCHAR(1) NULL COMMENT '发布状态\n',
  `create_date` DATE NULL,
  `update_date` DATE NULL,
  `create_by` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_t_tzgg_1_idx` (`create_by` ASC),
  CONSTRAINT `fk_t_tzgg_1`
    FOREIGN KEY (`create_by`)
    REFERENCES `mis`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '通知公告';


-- -----------------------------------------------------
-- Table `mis`.`bio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mis`.`bio` ;

CREATE TABLE IF NOT EXISTS `mis`.`bio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `flmc` VARCHAR(100) NULL COMMENT '分类名称',
  `t_swmc_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '生物名称\n';


-- -----------------------------------------------------
-- Table `mis`.`bio_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mis`.`bio_category` ;

CREATE TABLE IF NOT EXISTS `mis`.`bio_category` (
  `id` INT NOT NULL,
  `bio_cat_name` VARCHAR(45) NULL,
  `bio_cat_des` VARCHAR(45) NULL,
  `bio_parent_id` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_t_swwz_1`
    FOREIGN KEY (`id`)
    REFERENCES `mis`.`bio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '生物物种\n';


-- -----------------------------------------------------
-- Table `mis`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mis`.`role` ;

CREATE TABLE IF NOT EXISTS `mis`.`role` (
  `id` INT NOT NULL,
  `role_name` VARCHAR(45) NULL,
  `role_desc` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '用户角色\n';


-- -----------------------------------------------------
-- Table `mis`.`role_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mis`.`role_user` ;

CREATE TABLE IF NOT EXISTS `mis`.`role_user` (
  `id` INT NOT NULL,
  `user_id` MEDIUMTEXT NULL,
  `role_id` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_t_roles_users_1_idx` (`role_id` ASC),
  INDEX `fk_t_roles_users_2_idx` (`user_id` ASC)
)
ENGINE = InnoDB
COMMENT = '用户角色';


-- -----------------------------------------------------
-- Table `mis`.`resource`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mis`.`resource` ;

CREATE TABLE IF NOT EXISTS `mis`.`resource` (
  `id` INT NOT NULL,
  `resources` VARCHAR(100) NULL,
  `role_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_t_resources_1_idx` (`role_id` ASC)
  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mis`.`article`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mis`.`article` ;

CREATE TABLE IF NOT EXISTS `mis`.`article` (
  `id` INT NOT NULL,
  `subject` VARCHAR(100) NULL,
  `content` VARCHAR(2000) NULL,
  `create_date` DATE NULL,
  `create_by` INT NULL,
  `update_date` DATE NULL,
  `update_by` INT NULL,
  `status` INT NULL,
  `author` VARCHAR(45) NULL,
  `publish_date` DATE NULL,
  `periodicals` VARCHAR(45) NULL,
  `data_analyze_id` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_article_1_idx` (`create_by` ASC),
  INDEX `fk_article_2_idx` (`update_by` ASC),
  CONSTRAINT `fk_article_1`
    FOREIGN KEY (`create_by`)
    REFERENCES `mis`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_article_2`
    FOREIGN KEY (`update_by`)
    REFERENCES `mis`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mis`.`bio_specification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mis`.`bio_specification` ;

CREATE TABLE IF NOT EXISTS `mis`.`bio_specification` (
  `id` INT NOT NULL,
  `basic_info` BLOB NULL,
  `project_progress_brife_des` VARCHAR(45) NULL,
  `bio_cat_id` INT NULL,
  `basic_video_des_path` VARCHAR(45) NULL,
  `project_progress_detail_des` VARCHAR(1000) NULL,
  `database_id` INT NULL,
  `relative_acticle_id` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mis`.`images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mis`.`images` ;

CREATE TABLE IF NOT EXISTS `mis`.`images` (
  `id` INT NOT NULL,
  `path` VARCHAR(100) NULL,
  `foreign_id` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mis`.`scholar_interaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mis`.`scholar_interaction` ;

CREATE TABLE IF NOT EXISTS `mis`.`scholar_interaction` (
  `id` INT NOT NULL,
  `scholar_date` DATE NULL,
  `scholar_name` VARCHAR(45) NULL,
  `scholar_content` VARCHAR(1000) NULL,
  `create_by` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mis`.`data_analyze_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mis`.`data_analyze_category` ;

CREATE TABLE IF NOT EXISTS `mis`.`data_analyze_category` (
  `id` INT NOT NULL,
  `analyze_type_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mis`.`data_analyze`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mis`.`data_analyze` ;

CREATE TABLE IF NOT EXISTS `mis`.`data_analyze` (
  `id` INT NOT NULL,
  `data_analyze_cat_id` INT NULL,
  `data_analyze_title` VARCHAR(45) NULL,
  `data_analyze_link` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;